worlds:
  - world
hintList:
  - Type "/mx-cs-dealWithDevil" if you are stranded on an Island.
  - Radiant Sky blinds you, if you have no shelter.
  - Radiant Sky is harmless at Night.
  - Stay near Fire or other Sources of Warmth, to protect against Seering Cold.
  - Seering Cold is worse at Night.
  - The greater your Terror, the more Secrets you get from Horrific Whispers.
  - Assault Frequency and Serverity scale with your Terror.
  - To much Terror can make your Life harder.
  - Certain Blocks near the Bed can modify your Dreams.
  - Try igniting certain Blocks over Stone Bricks.
  - Try igniting certain Blocks over Glass.
  - Try igniting certain Blocks over Quarz.
  - Try igniting certain Blocks over Glowstone.
  - Try igniting Iron over certain other Blocks.
  - Try igniting Gold over certain other Blocks.
  - Try igniting Diamond over certain other Blocks.
  - Try igniting Emerald over certain other Blocks.
  - Try igniting Lapis Lazuli over certain other Blocks.
  - Try igniting Redstone over certain other Blocks.
  - Try igniting Coal over certain other Blocks.
  - Try igniting Quarz over certain other Blocks.
  - Try igniting Soul Sand over certain other Blocks.
  - Try igniting Bookshelfover certain other Blocks.
  - Try igniting Terracotta over certain other Blocks.
