name: MixedCatastrophes
version: ${project.version}
main: ch.mixin.main.MixedCatastrophesPlugin
api-version: 1.16
softdepend: [ IslandGenerator ]

commands:
  mx:
    description: The Root Command for MixedCatastrophes with Prefix mx.
  mx-cs:
    description: The Root Command for MixedCatastrophes with Prefix mx-cs.
permissions:
  mixedCatastrophes.reload:
    description: Reaload the Plugin.
    default: op
  mixedCatastrophes.catastrophes:
    description: Activate and deactivate Catastrophes.
    default: op
  mixedCatastrophes.aspect:
    description: Change Aspect Values.
    default: op
  mixedCatastrophes.weather:
    description: Change the Weather Catastrophes.
    default: op
  mixedCatastrophes.timeDistortion:
    description: Trigger Time Distortions.
    default: op
  mixedCatastrophes.starSplinter:
    description: Trigger Star Splinters.
    default: op
  mixedCatastrophes.whispers:
    description: Trigger Horriffic Whispers.
    default: op
  mixedCatastrophes.assault:
    description: Trigger Assault.
    default: op
  mixedCatastrophes.stalker:
    description: Cause and clear Stalkers.
    default: op
  mixedCatastrophes.*:
    description: All MixedCatastrophes Permissions.
    default: op
    children:
      mixedCatastrophes.reload: true
      mixedCatastrophes.catastrophes: true
      mixedCatastrophes.aspect: true
      mixedCatastrophes.weather: true
      mixedCatastrophes.timeDistortion: true
      mixedCatastrophes.starSplinter: true
      mixedCatastrophes.whispers: true
      mixedCatastrophes.assault: true
      mixedCatastrophes.stalker: true